# Generated by Django 4.0.3 on 2022-03-04 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0003_object_description_alter_object_location_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='lat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='object',
            name='lon',
            field=models.FloatField(default=0.0),
        ),
    ]
