# Generated by Django 4.0.3 on 2022-03-04 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0004_object_lat_object_lon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='object',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='object',
            name='lon',
        ),
    ]
